# Generated by Django 5.1.2 on 2024-10-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No_show')], default='CONFIRMED', max_length=20),
        ),
    ]
